import React from "react";
import { DataTable } from "@/components/ui/DataTable";
import Link from "next/link";
import { FileText, Download, Printer, Filter } from "lucide-react";

export default function ReportsCenterPage() {
  const columns = [
    { accessorKey: "title", header: "Report Title" },
    { accessorKey: "category", header: "Category" },
    { accessorKey: "generatedBy", header: "Generated By" },
    { accessorKey: "date", header: "Generated Date" },
    { accessorKey: "format", header: "Format" },
  ];

  const data = [
    { title: "Executive BIA Summary - Q3 2026", category: "Executive Summary", generatedBy: "John Admin", date: "2026-08-25", format: "PDF" },
    { title: "Critical Process RTO/RPO Matrix", category: "Operations", generatedBy: "Sarah BCM", date: "2026-08-22", format: "Excel" },
    { title: "Departmental Resilience Audit", category: "Compliance", generatedBy: "John Admin", date: "2026-08-20", format: "PDF" },
  ];

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-slate-900 dark:text-slate-100">Enterprise Reports Center</h1>
          <p className="text-sm text-slate-500">Generate, export, and review audit-ready business continuity and impact assessment reports.</p>
        </div>
        <div className="flex items-center gap-3">
          <button className="inline-flex items-center gap-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-medium rounded-md shadow-sm transition-colors">
            <FileText size={16} /> Generate New Report
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="bg-white dark:bg-slate-900 p-5 rounded-lg border border-slate-200 dark:border-slate-800 shadow-sm space-y-3">
          <div className="font-semibold text-slate-900 dark:text-slate-100 text-sm">Executive BIA Summary</div>
          <p className="text-xs text-slate-500">High-level overview for executive management detailing overall organization resilience and critical risk exposure.</p>
          <button className="text-xs font-medium text-indigo-600 hover:text-indigo-700 dark:text-indigo-400 flex items-center gap-1">
            <Download size={14} /> Export PDF Report
          </button>
        </div>
        <div className="bg-white dark:bg-slate-900 p-5 rounded-lg border border-slate-200 dark:border-slate-800 shadow-sm space-y-3">
          <div className="font-semibold text-slate-900 dark:text-slate-100 text-sm">Critical Process Register</div>
          <p className="text-xs text-slate-500">Comprehensive inventory of critical business workflows mapped against recovery time and recovery point objectives.</p>
          <button className="text-xs font-medium text-indigo-600 hover:text-indigo-700 dark:text-indigo-400 flex items-center gap-1">
            <Download size={14} /> Export Excel Matrix
          </button>
        </div>
        <div className="bg-white dark:bg-slate-900 p-5 rounded-lg border border-slate-200 dark:border-slate-800 shadow-sm space-y-3">
          <div className="font-semibold text-slate-900 dark:text-slate-100 text-sm">Compliance & Audit Pack</div>
          <p className="text-xs text-slate-500">Full audit trail including assessment version history, approvals, and review cycle compliance records.</p>
          <button className="text-xs font-medium text-indigo-600 hover:text-indigo-700 dark:text-indigo-400 flex items-center gap-1">
            <Download size={14} /> Export Audit Package
          </button>
        </div>
      </div>

      <div className="space-y-4 pt-2">
        <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100">Generated Reports History</h2>
        <DataTable columns={columns} data={data} />
      </div>
    </div>
  );
}
